name: Create ZIP File and deploy to Lambda layer

on:
  push:
    branches:
    - deploy

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create ZIP
        run: zip -r repo.zip .